#!/usr/bin/env bash

set -e

## Install the Drupal website
##
## Usage: fin drupal-install
##
## - Installs Composer dependencies
## - Installs Drupal
## - Imports all configuration from features
## - Runs the default migrations
## - Generates theme assets
## - Rebuilds the Drupal theme

function site_pre_install() {
  fin composer install
}

function site_install() {
  fin drush site:install config_installer -y \
    --account-name=admin \
    --account-pass=admin123
}

function site_post_install() {
  fin drush features:import:all -y
  fin drush migrate:import --all
  fin theme-build
  import_events
  fin exec drupal cache:rebuild
}

function import_events() {
  fin drush eval 'event_pull_cron()'
  fin drush advancedqueue:queue:process event_pull
}

site_pre_install
site_install
site_post_install
fin uli
