#!/usr/bin/env bash

set -e

## Install the Drupal website
##
## Usage: fin drupal-install
##
## - Installs Composer dependencies
## - Installs Drupal
## - Imports all configuration from features
## - Runs the default migrations
## - Generates theme assets
## - Rebuilds the Drupal theme

DB_PATH=".docksal/db"
DB_NAME="drupal"

function site_pre_install() {
  fin composer install
}

function site_install() {
  # If there is an exported database, import it.
  # Otherwise, install the site via Drush and run the post-install steps.
  if [ -f "${DB_PATH}/${DB_NAME}" ]; then
    zcat < "${DB_PATH}/${DB_NAME}" | fin db import

    fin exec drupal cache:rebuild
  else
    fin drush site:install config_installer -y \
      --account-name=admin \
      --account-pass=admin123

    site_post_install
    export_database
  fi
}

function site_post_install() {
  fin drush features:import:all -y
  fin drush migrate:import --all
  fin theme-build
  import_events
  fin exec drupal cache:rebuild
}

function export_database() {
  mkdir -p $DB_PATH

  fin db dump | gzip > "${DB_PATH}/${DB_NAME}"
}

function import_events() {
  fin drush core:cron
  fin drush advancedqueue:queue:process event_pull
}

site_pre_install
site_install
fin uli
