#!/usr/bin/env bash

set -e

## Install the Drupal website
##
## Usage: fin drupal-install
##
## - Installs Composer dependencies
## - Installs Drupal
## - Imports all configuration from features
## - Runs the default migrations
## - Generates theme assets
## - Rebuilds the Drupal theme

fin composer install

fin drush site:install config_installer -y \
  --account-name=admin \
  --account-pass=admin123

fin drush features:import:all -y
fin drush migrate:import --all

fin theme-build

fin exec drupal cache:rebuild

fin uli
