#!/usr/bin/env bash

set -e

## Refresh the Drupal website
##
## Usage: fin drupal-refresh
##
## - Installs Composer dependencies
## - Rebuilds the Drupal cache
## - Imports all configuration from features
## - Imports Drupal configuration
## - Runs database updates
## - Generates theme assets

fin composer install

fin drupal cache:rebuild
fin drush features:import:all -y
fin drupal config:import
fin drupal update:execute

fin theme-build

fin drupal cache:rebuild
