#!/usr/bin/env bash

set -e

## Build the theme assets
##
## Usage: fin theme-build

#: exec_target = cli

THEME_DIR="/var/www/${DOCROOT}/themes/custom/phpsouthwales"

pushd ${THEME_DIR}
yarn
yarn prod
popd
